### ISSUE TITLE
Unknown Commerce Type "Ecommerce - CheckoutOption"

### ISSUE THREAD

**Issue by vitali-ausianik** [mParticle/mparticle-web-sdk#116]
Hello Guys!

I use mParticle library in several projects to track checkout events. Worked fine for a long time, but recently I noticed that it produces following error: Unknown Commerce Type "Ecommerce - CheckoutOption". Could you please advice how ti fix it? I tried to search it via your docs and codebase, but without any luck.

Code snippet that produces mentioned error:
```
window.mParticle.eCommerce.logProductAction(window.mParticle.ProductActionType.CheckoutOption, [product1, product2], { ...attrs });
```

SDK Version: 2.12.5 (I got this version as a result of mParticle.getVersion() function)

**Comment by rmi22186** [comment]
Hi there - 

Thanks for reaching out!  I just tested and didn't have any issues, but I am wondering if it is looking for mparticle.ProductActionType before it is loaded. It sounds like perhaps you are using the snippet and not self hosting mparticle. Is that correct? We stub several of our methods, but eCommerce isn't one of them because of the size implications on the [mParticle loading snippet](https://docs.mparticle.com/developers/sdk/web/getting-started/#add-the-sdk-snippet).

Try putting your function inside a `ready` wrapper, which will only fire after mParticle initializes:
```
window.mParticle.ready(function() {
  window.mParticle.eCommerce.logProductAction......
});
```

**Comment by rmi22186** [comment]
Also - 2.12.5 was released 28 days ago...did issues start then, or did you notice it even more recently?

**Comment by vitali-ausianik** [comment]
Hi @rmi22186 ,
I'm not sure when did it appear first. I noticed it ~ two weeks ago, but probably it appeared earlier.
I have tried to wrap my code with ```window.mParticle.ready(...)``` but it didn't fix issue. 
Do you know when this type of error can be thrown? Probably it needs to have some specific configuration?

**Comment by vitali-ausianik** [comment]
Discussed in offline - issue was related to GTM configuration^ so this issue ca be closed. Thank you!
