### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by 2beens** [mParticle/mparticle-web-sdk#189]
Trying to use the Web SDK within a `NuxtJS` project with `TypeScript`.

I have found the type definitions in the [DefinitelyTyped Repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mparticle__web-sdk/index.d.ts), but - as these type definitions are not within the `dist` folder of the original (this) SDK, the integration is not really seamless, and it's a bit of a pain to make it all work for non-frontend experts.

Do you have plan to add/integrate the type definitions file alongside [the JS files here](https://github.com/mParticle/mparticle-web-sdk/tree/master/dist), or you have any suggestions or tips how to properly use the combination of this SDK and it's TypeDefinitions in a TypeScript project?

All help is much appreciated, thanks 🙌

**Comment by rmi22186** [comment]
Hi @2beens - Can you share the specific issues you are having with the DefinitelyTyped Repo?  You should be able to do 

```
npm install --save-dev @types/mparticle__web-sdk
```

And it should "just work".  It's entirely possible that there may be additional configuration that's needed for NuxtJS, but we haven't had any other reports from users about this.

Once we migrate fully to TypeScript we would be completely off of DefinitelyTyped and everything would be inside the package itself.

**Comment by 2beens** [comment]
Hi @rmi22186 , thanks for your quick response 🙌 

For example, we cannot use the following:
```ts
import { EventType, SDKEventAttrs } from '@mparticle/web-sdk'
```

Because those types are rather defined in a separate package `mparticle__web-sdk`, and not the "original" `@mparticle/web-sdk`.

So, you have plans to integrate the type definitions in the "original" web SDK, so we do not have to do these _acrobatics_ with DefinitelyTyped? Do you have any ETAs on that? :)

Thanks 🍻

**Comment by rmi22186** [comment]
Interesting.  I just tried this exact example that you provided and it seems to work in a very simple example app.  See the screenshot below:

![image](https://user-images.githubusercontent.com/5377436/146401442-ea634430-77e3-45dc-8cd2-25e83ac78fab.png)

I set up a super simple example here.  
[basic_ts_proj.zip](https://github.com/mParticle/mparticle-web-sdk/files/7728522/basic_ts_proj.zip)
When you open this does it work per the screenshot above?

Right now no ETA on including it in the dist/ folder right now, since DefinitelyTyped is a pretty comprehensive library and shouldn't require any additional acrobatics.  Let me know what happens when you open the above project.

**Comment by 2beens** [comment]
@rmi22186 Aah, OK, so now I am confident the issues are on our side, most probably with how the NuxtJS project is setup.

I really appreciate all the help here Robert, and will try to check your example app and how to properly integrate it in our app.
For that reason, I am closing the issue, and thanks again 🍻

**Comment by rmi22186** [comment]
Happy to help!
