### ISSUE TITLE
Add event context to sanitizeAttributes logger.warning

### ISSUE THREAD

**Issue by hartzis** [mParticle/mparticle-web-sdk#20]
We currently have a lot of these warnings which are helpful overall but it can be hard to trace them down.

Any thoughts on how this logging could be improved to help identify associated events that are now missing attributes because they are invalid?

https://github.com/mParticle/mparticle-web-sdk/blob/49b8fad1c37819dcc1d3fa5782bcc59d3ca1f805/src/helpers.js#L521-L524

**Comment by rmi22186** [comment]
Hi @hartzis - thanks for the insightful comment!

I agree it could be even more helpful to include an event name here. Passing the event name whenever a `sanitizeAttributes` is called and included in the warning could definitely work.

I can add this to our internal requests to be prioritized. Better yet, if you're up for it and need this sooner, since are open source we are open to contributions! :) Otherwise we'll get to this over the next few weeks.

**Comment by rmi22186** [comment]
Hi @hartzis - This has been implemented. If you use the snippet version of mParticle, nothing is needed and you will get the updates automatically. Otherwise, please upgrade to 2.11.16 of [@mparticle/web-sdk on npm](https://www.npmjs.com/package/@mparticle/web-sdk).

**Comment by hartzis** [comment]
@rmi22186 Thank you! this is awesome!
