### ISSUE TITLE
TypeScript types incompatible with packaged library

### ISSUE THREAD

**Issue by dasco144** [mParticle/mparticle-web-sdk#835]
When implementing the mParticle npm package, along with its types (provided by DefinitelyTyped), seems to have a few issues both when in the editor and when serving the app.

Importing enum or other types from the library gives me an error stating:

`Error: export 'EventType' (imported as 'EventType'
) was not found in '@mparticle/web-sdk' (possible exports: default)`

![Screenshot 2024-01-24 at 12 37 08](https://github.com/mParticle/mparticle-web-sdk/assets/10575019/2e932735-a646-4657-9be1-abbf70a41435)

Importing the default export gives me an error:

`Module
'"/Users/dsantiago/dev/research/mparticle-test/node_modules/@types/mparticle_web-sdk/index"' has no default export.
2 import MParticle, { EventType, SDKEventAttrs } from '@mparticle/web-sdk';`

![Screenshot 2024-01-24 at 12 37 08](https://github.com/mParticle/mparticle-web-sdk/assets/10575019/2e932735-a646-4657-9be1-abbf70a41435)

And in the editor:

![Screenshot 2024-01-24 at 12 29 54](https://github.com/mParticle/mparticle-web-sdk/assets/10575019/dd071678-ba07-4417-98bf-eabe971e5624)

I have an example repo [here](https://github.com/dasco144/mparticle-test) that shows the above issues.
Uninstalling the Typescript types, does seem to allow the app to build/serve but we lose the Typescript types.

Is there a more detailed guide on how to use the npm packaged library with the types in an Angular project?

**Comment by rmi22186** [comment]
Hi @dasco144 - 

The type of app framework (angular, react) shouldn't matter.  You can take a look at [our sample app](https://github.com/mParticle/mparticle-web-sample-apps/blob/main/core-sdk-samples/higgs-shop-sample-app/src/layouts/App/index.tsx).  I think the issue you are having is the casing of mParticle. You should import `mParticle` and not `MParticle` as shown in the sample app.

Let me know if that fixes things.  If not, you may need to open up a ticket directly with your customer success manager so that we can route this through the proper channels for debugging.

**Comment by dasco144** [comment]
Hi @rmi22186 

From what I understand, the casing doesn't matter here, as when importing from a default export, you can name the import as you like.

![image](https://github.com/mParticle/mparticle-web-sdk/assets/10575019/d1033995-dcaa-40e5-8dfc-fe439640e75a)

But, I may have managed to resolve this. Our TSConfig did not have `allowSyntheticDefaultImports` enabled, since we generally don't import files from libraries packaged the way the `@mparticle/web-sdk` exports them. Once that setting was enabled in the TSConfig compiler options, it did resolve the types correctly.

It does seem strange that this extra step is required though, as many other libraries do not. Maybe it's because many of the libraries in the Angular ecosystem are TypeScript libraries, where the exports are managed in a different way (most of the time it is named exports).

Is there a path to resolve that perhaps? Might help a lot of non-react devs, as it seems that TSConfig option is enabled by default in the current `create-react-app` and `vite` methods of creating react apps with TypeScript.
At the very least, it might be worth mentioning this in the docs somewhere (if there is a reference I did not see it 😅) for either the types (`@types/mparticle__web-sdk`) or the library itself (`@mparticle/web-sdk`)

**Comment by rmi22186** [comment]
That's my mistake for suggesting that.

Thank you for the suggestion about including @types in the docs.  While it does show a little linter squiggly line saying to try installing from there, I can understand that it isn't obvious for someone who hasn't had to use the @types packages before for non-TS projects.  I'll make a ticket for that.

We are in the process of migrating our JS --> TS in order to avoid having the extra @types/ step and to simplify things.

Glad you found a solution though!

**Comment by rmi22186** [comment]
I'll mark this as closed for now given the config setting you found.
